### ISSUE TITLE
Panic after attempting to begin road placement

### ISSUE THREAD

**Issue by chances** [citybound/citybound#48] opened 2016-12-25 22:48 UTC
Clicked to place a road at the end of an existing, built segment, caused simulation panic and app crash.

OS X El Captan 10.11.6

Console output:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Simulation Panic!
"called `Option::unwrap()` on a `None` value"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
```

**Comment by aeickhoff** [comment] 2016-12-25 23:20
Could you please run it with RUST_BACKTRACE=1

?

**Comment by chances** [comment] 2016-12-25 23:48
Running with `RUST_BACKTRACE=1` has no effect on output, at least on my local machine. I'm running from the packaged app. Perhaps the source is needed to provide proper backtraces. I'll try running from source later tonight or tomorrow.

```bash
$ /Applications/Citybound.app/Citybound RUST_BACKTRACE=1
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Simulation Panic!
"called `Option::unwrap()` on a `None` value"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
```

**Comment by Squarific** [comment] 2016-12-26 11:41
I think you have to place RUST_BACKGRACE=1 before the command

`$ RUST_BACKTRACE=1 /Applications/Citybound.app/Citybound`

**Comment by SimplyNaOH** [comment] 2016-12-26 18:15
I think this is the same as issue #50. I get the same on linux x64:

    thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
    note: Run with `RUST_BACKTRACE=1` for a backtrace.
    Simulation Panic!
    "called `Option::unwrap()` on a `None` value"
    thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323

with RUST-BACKTRACE=1:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:     0x559960f16138 - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x559960f1afff - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x559960f19e76 - std::panicking::default_hook::h852b4223c1c00c59
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x559960f1a527 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x559960f1a3b4 - std::panicking::begin_panic::hf6c488cee66e7f17
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x559960f1a2d9 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x559960f1a267 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
   8:     0x559960f5430d - core::panicking::panic_fmt::h9af671b78898cdba
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
   9:     0x559960f54244 - core::panicking::panic::h1a2d1a6b50eaa468
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:49
  10:     0x559960e09206 - <citybound::game::lanes_and_cars::planning::CurrentPlan as kay::messaging::Recipient<citybound::game::lanes_and_cars::planning::PlanControl>>::receive::h13badbdfe1d33dcb
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:21
                        at /home/anselm/cbr/src/game/lanes_and_cars/planning/mod.rs:395
  11:     0x559960e1275b - kay::actor_system::ActorSystem::add_inbox_helper::{{closure}}::he9e969878e67b74c
                        at /home/anselm/cbr/lib/kay/src/messaging.rs:12
                        at /home/anselm/cbr/lib/kay/src/actor_system.rs:149
  12:     0x559960e499e9 - kay::actor_system::ActorSystem::process_all_messages::h043416f9c9f3255b
                        at /home/anselm/cbr/lib/kay/src/actor_system.rs:204
                        at /home/anselm/cbr/lib/kay/src/actor_system.rs:216
  13:     0x559960d8a805 - std::panicking::try::do_call::hafa82fdf5cd46ec3
                        at /home/anselm/cbr/src/main.rs:105
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:255
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:356
  14:     0x559960f22ada - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  15:     0x559960dba311 - citybound::main::h1a2677eeb08d868c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:311
                        at /home/anselm/cbr/src/main.rs:104
  16:     0x559960f22ada - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  17:     0x559960f196ca - std::rt::lang_start::h14cbded5fe3cd915
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:311
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  18:     0x2b03b6b89290 - __libc_start_main
  19:     0x559960d5f178 - _start
  20:                0x0 - <unknown>
Simulation Panic!
"called `Option::unwrap()` on a `None` value"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:     0x559960f16138 - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x559960f1afff - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x559960f19e76 - std::panicking::default_hook::h852b4223c1c00c59
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x559960f1a527 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x559960f1a3b4 - std::panicking::begin_panic::hf6c488cee66e7f17
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x559960f1a2d9 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x559960f1a267 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
   8:     0x559960f5430d - core::panicking::panic_fmt::h9af671b78898cdba
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
   9:     0x559960f54244 - core::panicking::panic::h1a2d1a6b50eaa468
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:49
  10:     0x559960df8524 - <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next::h0a2ace9fe1972c1a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:21
                        at /home/anselm/cbr/src/game/lanes_and_cars/planning/mod.rs:105
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/ops.rs:2648
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/option.rs:383
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/iter/mod.rs:960
  11:     0x559960e06166 - <citybound::game::lanes_and_cars::planning::CurrentPlan as kay::messaging::Recipient<citybound::game::lanes_and_cars::planning::PlanControl>>::receive::h13badbdfe1d33dcb
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcollections/vec.rs:1528
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/iter/iterator.rs:1196
                        at /home/anselm/cbr/src/game/lanes_and_cars/planning/mod.rs:101
  12:     0x559960e1275b - kay::actor_system::ActorSystem::add_inbox_helper::{{closure}}::he9e969878e67b74c
                        at /home/anselm/cbr/lib/kay/src/messaging.rs:12
                        at /home/anselm/cbr/lib/kay/src/actor_system.rs:149
  13:     0x559960e499e9 - kay::actor_system::ActorSystem::process_all_messages::h043416f9c9f3255b
                        at /home/anselm/cbr/lib/kay/src/actor_system.rs:204
                        at /home/anselm/cbr/lib/kay/src/actor_system.rs:216
  14:     0x559960dba1ed - citybound::main::h1a2677eeb08d868c
                        at /home/anselm/cbr/src/main.rs:96
  15:     0x559960f22ada - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  16:     0x559960f196ca - std::rt::lang_start::h14cbded5fe3cd915
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:311
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  17:     0x2b03b6b89290 - __libc_start_main
  18:     0x559960d5f178 - _start
  19:                0x0 - <unknown>
```

**Comment by chances** [comment] 2016-12-28 17:49
Here's the full backtrace using the suggestion by @Squarific on OS X 10.11.6:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:        0x10a1576a8 - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:        0x10a15b11f - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:        0x10a15a13f - std::panicking::default_hook::h852b4223c1c00c59
   4:        0x10a15a766 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:        0x10a15a604 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:        0x10a15a522 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:        0x10a15a487 - rust_begin_unwind
   8:        0x10a184600 - core::panicking::panic_fmt::h9af671b78898cdba
   9:        0x10a184504 - core::panicking::panic::h1a2d1a6b50eaa468
  10:        0x10a0aa139 - citybound::game::lanes_and_cars::planning::CurrentPlan::create_draggables::h1e96e0601363abac
  11:        0x10a0a2c6c - <citybound::game::lanes_and_cars::planning::CurrentPlan as kay::messaging::Recipient<citybound::game::lanes_and_cars::planning::PlanControl>>::receive::h79409512bae5538e
  12:        0x10a0b1f7b - kay::actor_system::ActorSystem::add_inbox_helper::{{closure}}::h17b27b9347bcb373
  13:        0x10a0e9ad9 - kay::actor_system::ActorSystem::process_all_messages::hbb9ee17d1ec45290
  14:        0x10a027855 - std::panicking::try::do_call::hc38e36e35669cb34
  15:        0x10a15b6da - __rust_maybe_catch_panic
  16:        0x10a057ae1 - citybound::main::hb708e35856bec16c
  17:        0x10a15b6da - __rust_maybe_catch_panic
  18:        0x10a159c26 - std::rt::lang_start::h14cbded5fe3cd915
Simulation Panic!
"called `Option::unwrap()` on a `None` value"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:        0x10a1576a8 - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:        0x10a15b11f - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:        0x10a15a13f - std::panicking::default_hook::h852b4223c1c00c59
   4:        0x10a15a766 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:        0x10a15a604 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:        0x10a15a522 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:        0x10a15a487 - rust_begin_unwind
   8:        0x10a184600 - core::panicking::panic_fmt::h9af671b78898cdba
   9:        0x10a184504 - core::panicking::panic::h1a2d1a6b50eaa468
  10:        0x10a097394 - <core::iter::Map<I, F> as core::iter::iterator::Iterator>::next::hc86b26dbd3352010
  11:        0x10a0a5394 - <citybound::game::lanes_and_cars::planning::CurrentPlan as kay::messaging::Recipient<citybound::game::lanes_and_cars::planning::PlanControl>>::receive::h79409512bae5538e
  12:        0x10a0b1f7b - kay::actor_system::ActorSystem::add_inbox_helper::{{closure}}::h17b27b9347bcb373
  13:        0x10a0e9ad9 - kay::actor_system::ActorSystem::process_all_messages::hbb9ee17d1ec45290
  14:        0x10a057994 - citybound::main::hb708e35856bec16c
  15:        0x10a15b6da - __rust_maybe_catch_panic
  16:        0x10a159c26 - std::rt::lang_start::h14cbded5fe3cd915
```

**Comment by chances** [comment] 2016-12-29 11:32
Seems like a duplicate of #37

**Comment by aeickhoff** [comment] 2017-01-11 18:04
Also duplicate of #86

**Closed by aeickhoff** 2017-01-11 18:04 UTC
