### ISSUE TITLE
Car spawning/despawning issue

### ISSUE THREAD

**Issue by kingoflolz** [citybound/citybound#125] opened 2017-02-02 08:35 UTC
Very interesting issue, that takes a lot of time to reproduce D:

Create a simple intersection, spawn it full of cars, and then wait for them to all despawn/reach their destination.

Now you cannot spawn any more cars!

**Comment by aeickhoff** [comment] 2017-02-02 09:52
I know what this is caused by, but since spawning cars is also just a debug feature, I won't fix it

**Closed by aeickhoff** 2017-02-02 09:52 UTC
