### ISSUE TITLE
Compiled 'live build' silently crashes on windows

### ISSUE THREAD

**Issue by Rubyjunk** [citybound/citybound#295] opened 2018-09-22 22:55 UTC
Running the live build on windows will spontaneously crash after ~1-2 minutes of playing for no apparent reason. Console gets spammed with 'No road boundary found' when trying to zone things?

**Comment by aeickhoff** [comment] 2018-09-24 13:42
This message is harmless, the crash is not. Likely duplicate of #301

**Closed by aeickhoff** 2018-09-24 13:42 UTC
