### ISSUE TITLE
simulation grows the city very slow - different ideas / reasons

### ISSUE THREAD

**Issue by CarstenBaumannH** [citybound/citybound#324] opened 2018-10-08 22:32 UTC
Hi,

I developed a network of streets and implemented successfully a lot of different areas (which is easier on a slow machine, simulation brakes are much more seldom).

Then some buildings spawned in the commercial area. But it seems that at maximum 4 buildings are created in this area, not depending on the size of the area.

Also, cars driving in circles in a complex network of streets. They take 4 crossroads (with for fixed points A, B, C, D) and drive from point to point again and again. The simulated time is not important, the cars drive permanently 24h in this circle.
It seems that the development of the city is slowing down because of that. Maybe because the resources (money, manpower, groceries) of the employees are not coming to their goal!? I don't know how deep the simulation is already developed.
After a lot of time new cars coming from outside the town. The city is still developing slow. But the more the city is growing and new cars coming to town from outside, the speed of the city growing raises up. But also more an more cars take part in driving a circle or creating another circle.

Overall the city seems to develop very slowly, especially in the beginnings it needs some simulated days to create one, two or three buildings.
Also, it seems that the town is not developing without agricultural zones.

Hopefully, I was able to describe some problems of the game I discovered understandably and my ideas can support you detecting the problems.

For questions feel free to ask me. :)

**Comment by CarstenBaumannH** [comment] 2019-02-25 22:13
Still having this problemin the last January release. Especially the phenomen "carss driving in circles".

Also found out that some cars keep staying on the same place all long time. That happens often when I add lines to a street. I get the information "Could not find actor transport::lane#..Lane...".

**Comment by aeickhoff** [comment] 2019-03-02 16:04
Thank you for investigating this so thoroughly. The building development speed should be addressed by now. The "cars going in circles" is still a problem that I'm working on. Closing this as a duplicate of #308 for now.

**Closed by aeickhoff** 2019-03-02 16:04 UTC
