### ISSUE TITLE
Crash in planning mode (renderer)

### ISSUE THREAD

**Issue by TimGoll** [citybound/citybound#312] opened 2018-09-27 07:35 UTC
the renderer side has a null error, reloading the page does not solve this problem, it still happens

I tried to build a huge road-circle and this error occured after about 10 setpoints were set

![image](https://user-images.githubusercontent.com/13639408/46130062-a101b180-c238-11e8-8423-33299b7912d0.png)

**Comment by aeickhoff** [comment] 2018-09-27 08:28
This is a duplicate of #305, thanks for reporting and especially for including the console output! Otherwise I wouldn't have been able to see what the problem is.

**Closed by aeickhoff** 2018-09-27 08:28 UTC

**Comment by TimGoll** [comment] 2018-09-27 08:29
Ah sorry, I looked through the issues and haven't noticed it
