### ISSUE TITLE
Trying to Spawn Cowfarm

### ISSUE THREAD

**Issue by mallenwho** [citybound/citybound#300] opened 2018-09-23 22:44 UTC
Sometimes when I draw a road that looks like less than simple geometry (not too mean - a windy S connected to another road at the end) the simulator spits out muiltiple paragraphs of coordinates with the final line "Trying to Spawn Cowfarm". It hasn't crashed yet, however the road tool has reduced to placing individual node points (blue circles), no roads to connect them. The server crashes after five nodes are placed. Not sure whether five clicks or five road nodes are what are causing it.

Overall, I've been getting a lot of crashes with sharp or curvy geometry, and intersections that should be well handled. I'm not sure whether it's the same bug but only sometimes manifesting in a mild form (the above paragraph) or something different. FYI I'm running the game in Win 10 Chrome, in a portrait 16:9 tab.

EDIT: Same error occurs with wall of coordinates then crash even when "trying to spawn cowfarm" isn't there, although "trying to spawn cowfarm" is still a bad sign. I guess its a lot associated with agriculture yet more often than not I get it when I haven't attempted to zone anything. This crash seems to be held off by exporting plan to live mode, as the game will still run, just with a bunch of buggy zoning and/or roads. Returning to planning mode gives me the same ticking clock of a few node clicks before a full crash. So far I haven't been able to build more than a block or two because of very frequent crashing.

**Comment by aeickhoff** [comment] 2018-09-26 10:53
The crashes you see are most likely caused by #301, please let me know if this is resolved in the newest live build. The "Trying to spawn Cowfarm" is harmless. If other issues persist, please create new issues for them. Thank you!

**Closed by aeickhoff** 2018-09-26 10:53 UTC
