### ISSUE TITLE
Citybound crashing upon startup

### ISSUE THREAD

**Issue by VeeTHis** [citybound/citybound#145] opened 2017-02-05 00:31 UTC
Whenever I open the executable, the program opens for a split second and then instantly closes. Below is what the command prompt window said.
`Thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: NoVersion', C:\bot\slave\nightly-dist-rustc-win-gnu-64\build\src\libcore\result.rs:845 note: Run with 'RUST_BACKTRACE=1' for a backtrace.`
My graphics card is an Intel G45/G43 Express Chipset.

**Comment by crener** [comment] 2017-10-25 23:59
Could this be because of lack of support for the graphics API from the chipset?

"Microsoft DirectX* 10, Shader Model 4.0, and OpenGL* 2.0" [- Intel spec (PDF)](https://www.intel.com/assets/pdf/prodbrief/319946.pdf)

I don't know what Citybound uses for rendering but am going to assume it is at least OpenGl 3.0 or DX11?

**Comment by aeickhoff** [comment] 2017-10-26 10:09
I'm not exactly sure, since I'm just using default settings of my graphics library, but I think it uses OpenGL 3.0. Thanks for inquiring, @crener !

**Comment by IceAge0121** [comment] 2017-11-03 21:25
I'm having the same issue. Windows 10 reports that "citybound.exe has stopped working". I do briefly see the CityBound graphical interface. I'm not sure what the command line reports, as it disappears too quickly. As for graphics, I'm using Intel HD 5500, usually default settings. Normally I don't have any issues running games.

**Comment by aeickhoff** [comment] 2017-11-03 22:02
@IceAge0121 Can you please check if you have a `cb_last_error.txt` in your `%TMP%` folder and if yes paste its content here? Thank you!

**Comment by IceAge0121** [comment] 2017-11-03 22:05
Don't seem to have that file. I'll screenshot in case I got the wrong location:

![image](https://user-images.githubusercontent.com/32278956/32397720-9bcc1a3a-c0c1-11e7-9405-dc10260a04a1.png)

**Comment by aeickhoff** [comment] 2017-11-03 22:53
Thank you, that's exactly where it should be. But maybe the game crashes even before it can write out the error file. Could you please open a command line in the folder where you have downloaded Citybound and then run it from the command line with `citybound.exe`. Then you should be able to see all output without it going away.

**Comment by IceAge0121** [comment] 2017-11-03 23:03
You're welcome! Love what you've done far. This new release has got me so excited! The day/night cycle and economy is so realistic compared to anything else I've seen! Okay, enough of that :) Here you go: 

![image](https://user-images.githubusercontent.com/32278956/32399032-65b11b78-c0c9-11e7-8d81-c89f6e53b642.png)

**Comment by aeickhoff** [comment] 2017-11-03 23:31
Thank you @IceAge0121! The missing files are normal and fine. Your issue (the last line) is actually a duplicate of #210, which I also wasn't able to reproduce yet :/

**Comment by aeickhoff** [comment] 2018-08-10 17:39
This will be obsolete in the next version, which will fully rely on a browser UI.

**Closed by aeickhoff** 2018-08-10 17:39 UTC
Labels: P Bug, T Graphics
