### ISSUE TITLE
strange behavior while building roads that cross themselves  

### ISSUE THREAD

**Issue by MiniDigger** [citybound/citybound#39] opened 2016-12-25 15:24 UTC
this is the road I was trying to build (in three steps)
![http://i.minidigger.me/2016/12/citybound-windows_25_16-16-21.png](http://i.minidigger.me/2016/12/citybound-windows_25_16-16-21.png)

sometimes it crashes like this:
![http://i.minidigger.me/2016/12/Hyper_25_16-15-39.png](http://i.minidigger.me/2016/12/Hyper_25_16-15-39.png)
sometimes it doesn't build the circle:
![http://i.minidigger.me/2016/12/citybound-windows_25_16-17-19.png](http://i.minidigger.me/2016/12/citybound-windows_25_16-17-19.png)
the roads are still there, they just don't get build:
![http://i.minidigger.me/2016/12/citybound-windows_25_16-20-42.png](http://i.minidigger.me/2016/12/citybound-windows_25_16-20-42.png)
when you click the "ghost roads", you get this exception:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Simulation Panic!
"called `Option::unwrap()` on a `None` value"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:323```

**Comment by Tomnewsom** [comment] 2016-12-25 19:38
Duplicate of https://github.com/citybound/citybound/issues/35

**Comment by aeickhoff** [comment] 2016-12-25 20:04
Closing as duplicate of #35

**Closed by aeickhoff** 2016-12-25 20:04 UTC
