### ISSUE TITLE
Assertion failed while planning road: Failed to build the 2d convex hull of this point cloud.

### ISSUE THREAD

**Issue by mateon1** [citybound/citybound#232] opened 2017-11-16 22:49 UTC
This issue happened when placing a new road plan along a long, near-infinite road.

This happens within ncollide code. It assumes that it gets two different points to be able to build a complex hull, but the points it gets are equal.

I have an rr recording of this crash if more info is needed. (for my reference: `.local/share/rr/citybound-13`)

<details>
<summary> Error report </summary>

```gdb
SIMULATION BROKE :(

WHAT HAPPENED:
Failed to build the 2d convex hull of this point cloud.

WHERE IT HAPPENED:
at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_transformation-0.5.0/convex_hull.rs, line 763

WHERE EXACTLY:
stack backtrace:
   0:     0x55b076c1276e - backtrace::backtrace::libunwind::trace
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.4/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.4/src/backtrace/mod.rs:42
   1:     0x55b07698cfb4 - citybound::core::init::set_error_hook::{{closure}}
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.4/src/capture.rs:88
   2:     0x55b076c16928 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   3:     0x55b07694cf53 - std::panicking::begin_panic<&str>
                        at /checkout/src/libstd/panicking.rs:538
   4:     0x55b0769bd349 - ncollide_transformation::convex_hull::get_initial_polyline<nalgebra::structs::point::Point2<f32>>
                        at /shared/dev/rust/citybound/<panic macros>:3
                         - ncollide_transformation::convex_hull::convex_hull2_idx<nalgebra::structs::point::Point2<f32>>
                        at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_transformation-0.5.0/convex_hull.rs:681
                         - descartes::path::convex_hull<stagemaster::geometry::CPath>
                        at /shared/dev/rust/citybound/engine/descartes/src/path.rs:243
                         - citybound::transport::planning::road_result_steps::find_intersections::{{closure}}
                        at game/transport/planning/road_result_steps.rs:38
                         - core::iter::{{impl}}::next<citybound::transport::planning::road_plan::Intersection,citybound::core::disjoint_sets::SetsIterator<nalgebra::structs::point::Point2<f32>>,closure>
                        at /checkout/src/libcore/iter/mod.rs:1331
                         - compact::compact_vec::{{impl}}::from_iter<citybound::transport::planning::road_plan::Intersection,allocators::DefaultHeap,core::iter::FilterMap<citybound::core::disjoint_sets::SetsIterator<nalgebra::structs::point::Point2<f32>>, closure>>
                        at /shared/dev/rust/citybound/engine/compact/src/compact_vec.rs:461
                         - core::iter::iterator::Iterator::collect<core::iter::FilterMap<citybound::core::disjoint_sets::SetsIterator<nalgebra::structs::point::Point2<f32>>, closure>,compact::compact_vec::CompactVec<citybound::transport::planning::road_plan::Intersection, allocators::DefaultHeap>>
                        at /checkout/src/libcore/iter/iterator.rs:1298
                         - citybound::transport::planning::road_result_steps::find_intersections
                        at game/transport/planning/road_result_steps.rs:35
   5:     0x55b0769fd97c - citybound::transport::planning::road_plan::{{impl}}::get_result
                        at game/transport/planning/road_plan.rs:130
                         - citybound::planning::plan::{{impl}}::get_result
                        at game/planning/plan.rs:19
   6:     0x55b076a1ae05 - citybound::planning::materialized_reality::{{impl}}::simulate
                        at game/planning/materialized_reality/mod.rs:48
                         - citybound::planning::materialized_reality::kay_auto::auto_setup::{{closure}}
                        at game/planning/materialized_reality/kay_auto.rs:77
   7:     0x55b0768f9b39 - kay::swarm::{{impl}}::receive_instance<citybound::planning::materialized_reality::MaterializedReality,citybound::planning::materialized_reality::kay_auto::MSG_MaterializedReality_simulate,closure>
                        at /shared/dev/rust/citybound/engine/kay/src/swarm.rs:157
                         - kay::swarm::{{impl}}::dispatch_packet<citybound::planning::materialized_reality::MaterializedReality,citybound::planning::materialized_reality::kay_auto::MSG_MaterializedReality_simulate,closure>
                        at /shared/dev/rust/citybound/engine/kay/src/swarm.rs:265
                         - kay::actor_system::{{impl}}::add_handler::{{closure}}<citybound::planning::materialized_reality::MaterializedReality,citybound::planning::materialized_reality::kay_auto::MSG_MaterializedReality_simulate,closure>
                        at /shared/dev/rust/citybound/engine/kay/src/actor_system.rs:141
   8:     0x55b076b3627f - kay::actor_system::{{impl}}::single_message_cycle
                        at engine/kay/src/actor_system.rs:240
                         - kay::actor_system::{{impl}}::process_all_messages::{{closure}}
                        at engine/kay/src/actor_system.rs:266
                         - core::ops::function::FnOnce::call_once<closure,()>
                        at /checkout/src/libcore/ops/function.rs:223
                         - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:300
                         - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:480
                         - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /checkout/src/libpanic_unwind/lib.rs:99
                         - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panic.rs:365
                         - kay::actor_system::{{impl}}::process_all_messages
                        at engine/kay/src/actor_system.rs:265
   9:     0x55b076a6fc90 - citybound::main::{{closure}}
                        at game/main.rs:127
  10:     0x55b076a7af30 - main
  11:     0x7f347f5d12e0 - __libc_start_main
  12:     0x55b0768c8ce9 - _start
  13:                0x0 - <unknown>
```
</details>

**Comment by aeickhoff** [comment] 2018-08-10 17:35
Duplicate of #259

**Closed by aeickhoff** 2018-08-10 17:35 UTC
