### ISSUE TITLE
Game crashes when trying to "undo" with unfinished road

### ISSUE THREAD

**Issue by tml** [citybound/citybound#331] opened 2018-11-23 22:44 UTC
I hit the "Undo" button while placing a first road segment, because I wanted to change the start point. The game crashed (see error report below) and when I start the server again, I have no proposals available.

![image](https://user-images.githubusercontent.com/35148/48961971-b6dcdb80-ef36-11e8-87b1-0c164aa56b32.png)

SIMULATION BROKE :(

HOW TO REPORT BUGS:
https://github.com/citybound/citybound/blob/master/CONTRIBUTING.md#reporting-bugs

WHAT HAPPENED:
Expected gesture (that point should be added to) to exist!

WHERE IT HAPPENED:
at libcore\option.rs, line 1010

WHERE EXACTLY:
stack backtrace:
   0:     0x7ff713551227 - <no info>
   1:     0x7ff713550d1e - <no info>
   2:     0x7ff713550d9d - <no info>
   3:     0x7ff7134b27f2 - <no info>
   4:     0x7ff7138d34b2 - <no info>
   5:     0x7ff7138d2fb4 - <no info>
   6:     0x7ff7138d2e99 - <no info>
   7:     0x7ff7138ebe5c - <no info>
   8:     0x7ff7138ebed2 - <no info>
   9:     0x7ff71374197a - <no info>
  10:     0x7ff71373be68 - <no info>
  11:     0x7ff71377092a - <no info>
  12:     0x7ff71384650e - <no info>
  13:     0x7ff7138ea952 - <no info>
  14:     0x7ff71384e186 - <no info>
  15:     0x7ff713483f75 - <no info>
  16:     0x7ff7134860c6 - <no info>
  17:     0x7ff7138ea952 - <no info>
  18:     0x7ff71349b9b5 - <no info>
  19:     0x7ff7138dfc72 - <no info>
  20:     0x7ff7138e1c89 - <no info>
  21:     0x7ff822c03034 - BaseThreadInitThunk

**Comment by aeickhoff** [comment] 2019-03-02 16:05
Thanks for the report! This is a duplicate of #321

**Closed by aeickhoff** 2019-03-02 16:05 UTC
