### ISSUE TITLE
Cannot re-launch on Mac 10.12.1

### ISSUE THREAD

**Issue by ianpaschal** [citybound/citybound#52] opened 2016-12-26 09:35 UTC
Created a Panic by overlapping too many roads (gotta test those intersections!).

CMD+Q to quit the game, however double clicking the .app to restart it launches the app without any new windows appearing. Only option is to force quit the .app.

**Comment by aeickhoff** [comment] 2016-12-26 12:12
Duplicate of #34

**Closed** 2016-12-26 12:12 UTC
