### ISSUE TITLE
Unknown Simulation Issue

### ISSUE THREAD

**Issue by tfinnm** [citybound/citybound#260] opened 2018-03-25 19:06 UTC
SIMULATION BROKE :(

HOW TO REPORT BUGS:
https://github.com/citybound/citybound/blob/master/CONTRIBUTING.md#reporting-bugs

WHAT HAPPENED:
index out of bounds: the len is 6 but the index is 6

WHERE IT HAPPENED:
at game\transport\microtraffic\mod.rs, line 438

WHERE EXACTLY:
stack backtrace:
   0:     0x7ff68588bb72 - <no info>
   1:     0x7ff685889fd3 - <no info>
   2:     0x7ff68553bc17 - <no info>
   3:     0x7ff6858b3214 - <no info>
   4:     0x7ff6858b3019 - <no info>
   5:     0x7ff6858b2f62 - <no info>
   6:     0x7ff6858b2ed0 - <no info>
   7:     0x7ff6858b94cf - <no info>
   8:     0x7ff6858b9481 - <no info>
   9:     0x7ff685620845 - <no info>
  10:     0x7ff6855a00f8 - <no info>
  11:     0x7ff6857dd743 - <no info>
  12:     0x7ff6857d3948 - <no info>
  13:     0x7ff6858b4342 - <no info>
  14:     0x7ff6857d7389 - <no info>
  15:     0x7ff6857d58e3 - <no info>
  16:     0x7ff6857dd8e3 - <no info>
  17:     0x7ff68568e1f5 - <no info>
  18:     0x7ff6858b4342 - <no info>
  19:     0x7ff685606c95 - <no info>
  20:     0x7ff6856a7d27 - <no info>
  21:     0x7ff6858b17cc - <no info>
  22:     0x7ffdb7581fe4 - BaseThreadInitThunk

**Comment by aeickhoff** [comment] 2018-09-26 17:29
Duplicate of #311 most likely

**Closed by aeickhoff** 2018-09-26 17:29 UTC
