### ISSUE TITLE
Clicking/Dragging mouse on a built street crashes the game

### ISSUE THREAD

**Issue by jlga** [citybound/citybound#47] opened 2016-12-25 22:37 UTC
When building a road, after it has finished, if you click/drag on a road the game crashes.

Error message: 
thread 'main' panicked at 'called `Option::unwrap()` on a \`None\` value', ../src/libcore\option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Simulation Panic!
"called `Option::unwrap()` on a `None` value"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:323

**Comment by jacwah** [comment] 2016-12-27 19:22
Here is the backtrace I am getting:
```
$ RUST_BACKTRACE=1 Downloads/Citybound.app/Citybound 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:        0x106a6f6a8 - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:        0x106a7311f - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:        0x106a7213f - std::panicking::default_hook::h852b4223c1c00c59
   4:        0x106a72766 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:        0x106a72604 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:        0x106a72522 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:        0x106a72487 - rust_begin_unwind
   8:        0x106a9c600 - core::panicking::panic_fmt::h9af671b78898cdba
   9:        0x106a9c504 - core::panicking::panic::h1a2d1a6b50eaa468
  10:        0x1069c0637 - <citybound::game::lanes_and_cars::planning::CurrentPlan as kay::messaging::Recipient<citybound::game::lanes_and_cars::planning::PlanControl>>::receive::h79409512bae5538e
  11:        0x1069c9f7b - kay::actor_system::ActorSystem::add_inbox_helper::{{closure}}::h17b27b9347bcb373
  12:        0x106a01ad9 - kay::actor_system::ActorSystem::process_all_messages::hbb9ee17d1ec45290
  13:        0x10693f855 - std::panicking::try::do_call::hc38e36e35669cb34
  14:        0x106a736da - __rust_maybe_catch_panic
  15:        0x10696fae1 - citybound::main::hb708e35856bec16c
  16:        0x106a736da - __rust_maybe_catch_panic
  17:        0x106a71c26 - std::rt::lang_start::h14cbded5fe3cd915
Simulation Panic!
"called `Option::unwrap()` on a `None` value"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:        0x106a6f6a8 - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:        0x106a7311f - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:        0x106a7213f - std::panicking::default_hook::h852b4223c1c00c59
   4:        0x106a72766 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:        0x106a72604 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:        0x106a72522 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:        0x106a72487 - rust_begin_unwind
   8:        0x106a9c600 - core::panicking::panic_fmt::h9af671b78898cdba
   9:        0x106a9c504 - core::panicking::panic::h1a2d1a6b50eaa468
  10:        0x1069c0637 - <citybound::game::lanes_and_cars::planning::CurrentPlan as kay::messaging::Recipient<citybound::game::lanes_and_cars::planning::PlanControl>>::receive::h79409512bae5538e
  11:        0x1069c9f7b - kay::actor_system::ActorSystem::add_inbox_helper::{{closure}}::h17b27b9347bcb373
  12:        0x106a01ad9 - kay::actor_system::ActorSystem::process_all_messages::hbb9ee17d1ec45290
  13:        0x10696f994 - citybound::main::hb708e35856bec16c
  14:        0x106a736da - __rust_maybe_catch_panic
  15:        0x106a71c26 - std::rt::lang_start::h14cbded5fe3cd915
```

**Comment by chances** [comment] 2016-12-29 11:37
Possible duplicate of #37?

**Comment by aeickhoff** [comment] 2017-01-11 18:03
Closing as duplicate of #86

**Closed by aeickhoff** 2017-01-11 18:03 UTC
