### ISSUE TITLE
Tried to remove a household not in the building

### ISSUE THREAD

**Issue by Tomnewsom** [citybound/citybound#242] opened 2017-12-08 21:04 UTC
Have had this all three times I've attempted building a simple layout, after just a few minutes of play. No crazy road geometry, just a big trunk road with a bunch of criss-crossing 2-lane grids coming off it at verious points.

Repeatable on two completely different win10 systems

SIMULATION BROKE :(

HOW TO REPORT BUGS:
https://github.com/citybound/citybound/blob/master/CONTRIBUTING.md#reporting-bugs

WHAT HAPPENED:
Tried to remove a household not in the building

WHERE IT HAPPENED:
at src\libcore\option.rs, line 839

WHERE EXACTLY:
stack backtrace:
   0:     0x7ff6e073bb72 - <no info>
   1:     0x7ff6e0739fd3 - <no info>
   2:     0x7ff6e03ebc17 - <no info>
   3:     0x7ff6e0763214 - <no info>
   4:     0x7ff6e0763019 - <no info>
   5:     0x7ff6e0762f62 - <no info>
   6:     0x7ff6e0762ed0 - <no info>
   7:     0x7ff6e07694cf - <no info>
   8:     0x7ff6e0769540 - <no info>
   9:     0x7ff6e05b40c8 - <no info>
  10:     0x7ff6e048e4f0 - <no info>
  11:     0x7ff6e068d743 - <no info>
  12:     0x7ff6e0683948 - <no info>
  13:     0x7ff6e0764342 - <no info>
  14:     0x7ff6e0687389 - <no info>
  15:     0x7ff6e06858e3 - <no info>
  16:     0x7ff6e068d8e3 - <no info>
  17:     0x7ff6e053e1f5 - <no info>
  18:     0x7ff6e0764342 - <no info>
  19:     0x7ff6e04b6c95 - <no info>
  20:     0x7ff6e0557d27 - <no info>
  21:     0x7ff6e07617cc - <no info>
  22:     0x7ffb63ac2774 - BaseThreadInitThunk

**Comment by aeickhoff** [comment] 2017-12-11 17:20
Closing this as a duplicate of #244, since there is more backtrace information. Thanks for reporting!

**Closed by aeickhoff** 2017-12-11 17:20 UTC
Labels: P Bug, T Economy
