### ISSUE TITLE
UI Broke while drawing road fast when zoomed out - Error: unreachable executed

### ISSUE THREAD

**Issue by theaustria** [citybound/citybound#330] opened 2018-11-11 17:19 UTC
**Description**: UI crashes when I place street nodes fast while being zoomed out. After reloading the page it crashes right after chosing a proposal.
**How to reproduce**: 

1. Start fresh game
2. Zoom out
3. Draw a road fast

**Screenshot**: ![uicrash](https://user-images.githubusercontent.com/1621312/48316014-11dd0d00-e5de-11e8-8889-be6ec05d288a.png)

**OS**: Mint 18.2 sonya
**Kernel**: x86_64 Linux 4.15.0-36-generic
**Browser**: Mozilla Firefox 63.0
**Citybound version**: v0.1.2-728-g88e0531

**Ingame output**:
```
Error: unreachable executed
__rust_start_panic in /cb_browser_ui.wasm:wasm-function[5320]:0x2e696a undefined:undefined
rust_panic in /cb_browser_ui.wasm:wasm-function[5316]:0x2e68f4 undefined:undefined
std::panicking::rust_panic_with_hook::h59b410f8f92fb42f in /cb_browser_ui.wasm:wasm-function[5311]:0x2e660c undefined:undefined
std::panicking::begin_panic::h7035f3376cc36844 in /cb_browser_ui.wasm:wasm-function[648]:0x6efba undefined:undefined
_$LT$michelangelo..mesh_grouper..MeshQueue$LT$K$GT$$GT$::push::h638f68481737d04d in /cb_browser_ui.wasm:wasm-function[326]:0x2a6e3 undefined:undefined
_$LT$michelangelo..mesh_grouper..MeshGrouper$LT$K$GT$$GT$::update::h492fb2b3c2fd3c6a in /cb_browser_ui.wasm:wasm-function[329]:0x2bc7f undefined:undefined
_$LT$cb_browser_ui..planning_browser..BrowserPlanningUI$u20$as$u20$cb_simulation..planning..ui..PlanningUI$GT$::on_proposal_preview_update::hfae214e03bbf7879 in /cb_browser_ui.wasm:wasm-function[287]:0x21b08 undefined:undefined
_$LT$kay..instance_store..InstanceStore$LT$A$GT$$GT$::dispatch_packet::h718e54ee6b0a4d7c in /cb_browser_ui.wasm:wasm-function[551]:0x627cb undefined:undefined
kay::actor_system::ActorSystem::add_handler::_$u7b$$u7b$closure$u7d$$u7d$::h8587821d07871c35 in /cb_browser_ui.wasm:wasm-function[183]:0xe099 undefined:undefined
kay::actor_system::ActorSystem::single_message_cycle::h1078bb46cf027c96 in /cb_browser_ui.wasm:wasm-function[4948]:0x2d08e5 undefined:undefined
std::panicking::try::do_call::h995995e3bb689d35 (.llvm.15242682403797609456) in /cb_browser_ui.wasm:wasm-function[4880]:0x2c84a1 undefined:undefined
__rust_maybe_catch_panic in /cb_browser_ui.wasm:wasm-function[5319]:0x2e6962 undefined:undefined
kay::actor_system::ActorSystem::process_all_messages::hf608e01cb954782b in /cb_browser_ui.wasm:wasm-function[4949]:0x2d0adc undefined:undefined
cb_browser_ui::MainLoop::frame::h9cdb0204bb601de9 in /cb_browser_ui.wasm:wasm-function[151]:0x725f undefined:undefined
_$LT$stdweb..webcore..newtype..Newtype$LT$$LP$stdweb..webcore..serialization..FunctionTag$C$$u20$$LP$A12$C$$RP$$RP$$C$$u20$stdweb..webcore..once..Once$LT$F$GT$$GT$$u20$as$u20$stdweb..webcore..serialization..FuncallAdapter$LT$F$GT$$GT$::funcall_adapter::h44a9e53dbd6fde9a in /cb_browser_ui.wasm:wasm-function[265]:0x1b904 undefined:undefined
dyncall in ../target/wasm32-unknown-unknown/release/cb_browser_ui.js 425:11
output in ../target/wasm32-unknown-unknown/release/cb_browser_ui.js 182:12
```
**Firefox console output**:
```
panicked at 'New meshes too big for one queue', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/michelangelo-0.1.4/src/mesh_grouper.rs:28:13 cb_browser_ui.js:695:53
	__extjs_c41297f1f679af47d6390b4b617d1a8375706933 cb_browser_ui.js:695:53
	cb_browser_ui::start::_$u7b$$u7b$closure$u7d$$u7d$::h6247842ac6e036f7 http://localhost:1234/cb_browser_ui.wasm:26744:2147483794
	std::panicking::rust_panic_with_hook::h59b410f8f92fb42f http://localhost:1234/cb_browser_ui.wasm:3040646:2147488959
	std::panicking::begin_panic::h7035f3376cc36844 http://localhost:1234/cb_browser_ui.wasm:454586:2147484296
	_$LT$michelangelo..mesh_grouper..MeshQueue$LT$K$GT$$GT$::push::h638f68481737d04d http://localhost:1234/cb_browser_ui.wasm:173795:2147483974
	_$LT$michelangelo..mesh_grouper..MeshGrouper$LT$K$GT$$GT$::update::h492fb2b3c2fd3c6a http://localhost:1234/cb_browser_ui.wasm:179327:2147483977
	_$LT$cb_browser_ui..planning_browser..BrowserPlanningUI$u20$as$u20$cb_simulation..planning..ui..PlanningUI$GT$::on_proposal_preview_update::hfae214e03bbf7879 http://localhost:1234/cb_browser_ui.wasm:137992:2147483935
	_$LT$kay..instance_store..InstanceStore$LT$A$GT$$GT$::dispatch_packet::h718e54ee6b0a4d7c http://localhost:1234/cb_browser_ui.wasm:403403:2147484199
	kay::actor_system::ActorSystem::add_handler::_$u7b$$u7b$closure$u7d$$u7d$::h8587821d07871c35 http://localhost:1234/cb_browser_ui.wasm:57497:2147483831
	kay::actor_system::ActorSystem::single_message_cycle::h1078bb46cf027c96 http://localhost:1234/cb_browser_ui.wasm:2951397:2147488596
	std::panicking::try::do_call::h995995e3bb689d35 (.llvm.15242682403797609456) http://localhost:1234/cb_browser_ui.wasm:2917537:2147488528
	__rust_maybe_catch_panic http://localhost:1234/cb_browser_ui.wasm:3041634:2147488967
	kay::actor_system::ActorSystem::process_all_messages::hf608e01cb954782b http://localhost:1234/cb_browser_ui.wasm:2951900:2147488597
	cb_browser_ui::MainLoop::frame::h9cdb0204bb601de9 http://localhost:1234/cb_browser_ui.wasm:29279:2147483799
	_$LT$stdweb..webcore..newtype..Newtype$LT$$LP$stdweb..webcore..serialization..FunctionTag$C$$u20$$LP$A12$C$$RP$$RP$$C$$u20$stdweb..webcore..once..Once$LT$F$GT$$GT$$u20$as$u20$stdweb..webcore..serialization..FuncallAdapter$LT$F$GT$$GT$::funcall_adapter::h44a9e53dbd6fde9a http://localhost:1234/cb_browser_ui.wasm:112900:2147483913
	parcelRequire<["7eTP"]</</</Module.STDWEB_PRIVATE.dyncall cb_browser_ui.js:425:11
	output cb_browser_ui.js:182:12
```
```
RuntimeError: unreachable executed cb_browser_ui.wasm:3041642:1
	__rust_start_panic http://localhost:1234/cb_browser_ui.wasm:3041642:2147488968
	rust_panic http://localhost:1234/cb_browser_ui.wasm:3041524:2147488964
	std::panicking::rust_panic_with_hook::h59b410f8f92fb42f http://localhost:1234/cb_browser_ui.wasm:3040780:2147488959
	std::panicking::begin_panic::h7035f3376cc36844 http://localhost:1234/cb_browser_ui.wasm:454586:2147484296
	_$LT$michelangelo..mesh_grouper..MeshQueue$LT$K$GT$$GT$::push::h638f68481737d04d http://localhost:1234/cb_browser_ui.wasm:173795:2147483974
	_$LT$michelangelo..mesh_grouper..MeshGrouper$LT$K$GT$$GT$::update::h492fb2b3c2fd3c6a http://localhost:1234/cb_browser_ui.wasm:179327:2147483977
	_$LT$cb_browser_ui..planning_browser..BrowserPlanningUI$u20$as$u20$cb_simulation..planning..ui..PlanningUI$GT$::on_proposal_preview_update::hfae214e03bbf7879 http://localhost:1234/cb_browser_ui.wasm:137992:2147483935
	_$LT$kay..instance_store..InstanceStore$LT$A$GT$$GT$::dispatch_packet::h718e54ee6b0a4d7c http://localhost:1234/cb_browser_ui.wasm:403403:2147484199
	kay::actor_system::ActorSystem::add_handler::_$u7b$$u7b$closure$u7d$$u7d$::h8587821d07871c35 http://localhost:1234/cb_browser_ui.wasm:57497:2147483831
	kay::actor_system::ActorSystem::single_message_cycle::h1078bb46cf027c96 http://localhost:1234/cb_browser_ui.wasm:2951397:2147488596
	std::panicking::try::do_call::h995995e3bb689d35 (.llvm.15242682403797609456) http://localhost:1234/cb_browser_ui.wasm:2917537:2147488528
	__rust_maybe_catch_panic http://localhost:1234/cb_browser_ui.wasm:3041634:2147488967
	kay::actor_system::ActorSystem::process_all_messages::hf608e01cb954782b http://localhost:1234/cb_browser_ui.wasm:2951900:2147488597
	cb_browser_ui::MainLoop::frame::h9cdb0204bb601de9 http://localhost:1234/cb_browser_ui.wasm:29279:2147483799
	_$LT$stdweb..webcore..newtype..Newtype$LT$$LP$stdweb..webcore..serialization..FunctionTag$C$$u20$$LP$A12$C$$RP$$RP$$C$$u20$stdweb..webcore..once..Once$LT$F$GT$$GT$$u20$as$u20$stdweb..webcore..serialization..FuncallAdapter$LT$F$GT$$GT$::funcall_adapter::h44a9e53dbd6fde9a http://localhost:1234/cb_browser_ui.wasm:112900:2147483913
	parcelRequire<["7eTP"]</</</Module.STDWEB_PRIVATE.dyncall cb_browser_ui.js:425:11
	output cb_browser_ui.js:182:12

```

**Comment by aeickhoff** [comment] 2019-03-02 16:09
Thank you for the very detailed report. This is a duplicate of #305

**Closed by aeickhoff** 2019-03-02 16:09 UTC
