### ISSUE TITLE
Crash without message on clicking existing road.

### ISSUE THREAD

**Issue by WazWaz** [citybound/citybound#50] opened 2016-12-26 00:51 UTC
1. Plan trivial road.
2. Build road.
3. Click anywhere on that road.
4. Both windows close.

Tested on Windows 10 x64

**Comment by chances** [comment] 2016-12-29 11:32
Possible duplicate of #37?

**Comment by aeickhoff** [comment] 2017-01-11 18:01
Closing as duplicate of #86

**Closed by aeickhoff** 2017-01-11 18:01 UTC
