### ISSUE TITLE
Simulation Broke - Failed to build the 2d convex hull of this point cloud

### ISSUE THREAD

**Issue by joshlf** [citybound/citybound#251] opened 2018-01-20 20:26 UTC
Version: 0.3.0 for Mac ([this download](https://github.com/citybound/citybound/releases/download/v0.3.0/citybound.app.zip))

Full message:

```text
SIMULATION BROKE :(

HOW TO REPORT BUGS:
https://github.com/citybound/citybound/blob/master/CONTRIBUTING.md#reporting-bugs

WHAT HAPPENED:
Failed to build the 2d convex hull of this point cloud.

WHERE IT HAPPENED:
at /Users/anselmeickhoff/.cargo/registry/src/github.com-1ecc6299db9ec823/ncollide_transformation-0.5.0/convex_hull.rs, line 763

WHERE EXACTLY:
stack backtrace:
   0:        0x109d9944e - backtrace::backtrace::trace::h1e071f7475579ad6
   1:        0x109d972cc - backtrace::capture::Backtrace::new::h47fff0208a22eb3b
   2:        0x109afa1fb - citybound::core::init::set_error_hook::_$u7b$$u7b$closure$u7d$$u7d$::h8906bc1c98c85a8d
   3:        0x109db5831 - std::panicking::rust_panic_with_hook::h2ec98db505607dac
   4:        0x109b89f17 - std::panicking::begin_panic::h949bcf9b0490df96
   5:        0x10997ee52 - ncollide_transformation::convex_hull::convex_hull2_idx::h0df0becf9247907d
   6:        0x109af8431 - descartes::path::convex_hull::h5b1f1654cbeda09c
   7:        0x1099748ac - _$LT$compact..compact_vec..CompactVec$LT$T$C$$u20$A$GT$$u20$as$u20$core..iter..traits..FromIterator$LT$T$GT$$GT$::from_iter::h84355cafb0ebd76d
   8:        0x109bc8544 - citybound::transport::planning::road_result_steps::find_intersections::hb9a5d829a9398568
   9:        0x109bd849c - citybound::planning::plan::Plan::get_result::h217999c43e006ac1
  10:        0x109b27e17 - citybound::planning::materialized_reality::MaterializedReality::simulate::hc72ced287cd1a6ce
  11:        0x109a3ad3b - _$LT$kay..swarm..Swarm$LT$A$GT$$GT$::dispatch_packet::h1f3ec307110918f0
  12:        0x1099b74dd - kay::actor_system::ActorSystem::add_handler::_$u7b$$u7b$closure$u7d$$u7d$::h96c5fe051295347c
  13:        0x109cdda20 - kay::actor_system::ActorSystem::single_message_cycle::h80316011f578ee66
  14:        0x109cd8017 - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h0a7853407cc7589c
  15:        0x109dc0b7c - __rust_maybe_catch_panic
  16:        0x109cd4f87 - std::panicking::try::hed42753cc33322e4
  17:        0x109cd9d3d - std::panic::catch_unwind::h237d3c5ab9aabdb0
  18:        0x109cddb9d - kay::actor_system::ActorSystem::process_all_messages::ha8a5a8656dbed9c7
  19:        0x109af949f - citybound::core::init::ensure_crossplatform_proper_thread::hc0b20e6835400548
  20:        0x109dc0b7c - __rust_maybe_catch_panic
  21:        0x109db5cf8 - std::rt::lang_start::h117e7b15e25564f6
```

**Comment by aeickhoff** [comment] 2018-08-10 17:32
Duplicate of #259

**Closed by aeickhoff** 2018-08-10 17:32 UTC
